<?php
define('_DB_SERVER_', 'mysql.hostinger.vn');
define('_DB_NAME_', 'u366837675_dung');
define('_DB_USER_', 'u366837675_root');
define('_DB_PASSWD_', 'dungtran123');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'MyISAM');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'hb35vKNUJOr4ZHrGPI4Rj0wfJYI4K699FZweexPi9ZcKkh0J9qXfH0fH');
define('_COOKIE_IV_', 'CpRhcyxt');
define('_PS_CREATION_DATE_', '2014-10-14');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'YB9dVSPq6Ygc6b0Xt7WNqMHLAQqeraMd');
define('_RIJNDAEL_IV_', 'D2pAX8W+8g6ZzROYzy1F4A==');
